# Generated by Django 3.0.8 on 2020-08-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='num',
            new_name='name',
        ),
        migrations.AddField(
            model_name='number',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
